<a href="https://colab.research.google.com/github/the-visionary/assignment1/blob/main/Copy_of_Assignment_1_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Steps to load extra files and download dataset.
!git clone "https://pradum22:143%40simplyGIT@github.com/the-visionary/assignment1.git"
import os
os.chdir('/content')
os.chdir('assignment1')
os.chdir('assignment1-part1')
assert (os.getcwd() == '/content/assignment1/assignment1-part1')

os.chdir('cifar10')
%run get_datasets.py
os.chdir('..')
assert (os.getcwd() == '/content/assignment1/assignment1-part1')

Cloning into 'assignment1'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 56 (delta 18), reused 32 (delta 4), pack-reused 0
Unpacking objects: 100% (56/56), done.
Downloading...


In [2]:
import os
os.chdir('/content/assignment1/assignment1-part1')

In [3]:
import random
import numpy as np
from data_process import get_CIFAR10_data, get_MUSHROOM_data
from scipy.spatial import distance
import models
%matplotlib inline

In [4]:
import importlib
import sys
importlib.reload(sys.modules['models'])
from models import SVM

# importlib.reload(models.SVM)

# Loading CIFAR-10

In the following cells we determine the number of images for each split and load the images.
<br /> 
TRAIN_IMAGES + VAL_IMAGES = (0, 50000]
, TEST_IMAGES = 10000

In [ ]:
# You can change these numbers for experimentation
# For submission we will use the default values 
TRAIN_IMAGES = 40000
VAL_IMAGES = 10000

In [ ]:
data = get_CIFAR10_data(TRAIN_IMAGES, VAL_IMAGES)
X_train_CIFAR, y_train_CIFAR = data['X_train'], data['y_train']
X_val_CIFAR, y_val_CIFAR = data['X_val'], data['y_val']
X_test_CIFAR, y_test_CIFAR = data['X_test'], data['y_test']
n_class_CIFAR = len(np.unique(y_test_CIFAR))

Convert the sets of images from dimensions of **(N, 3, 32, 32) -> (N, 3072)** where N is the number of images so that each **3x32x32** image is represented by a single vector.

In [ ]:
X_train_CIFAR = np.reshape(X_train_CIFAR, (X_train_CIFAR.shape[0], -1))
X_val_CIFAR = np.reshape(X_val_CIFAR, (X_val_CIFAR.shape[0], -1))
X_test_CIFAR = np.reshape(X_test_CIFAR, (X_test_CIFAR.shape[0], -1))

# Loading Mushroom

In the following cells we determine the splitting of the mushroom dataset.
<br /> TRAINING + VALIDATION = 0.8, TESTING = 0.2

In [5]:
# TRAINING = 0.6 indicates 60% of the data is used as the training dataset.
VALIDATION = 0.2

In [6]:
data = get_MUSHROOM_data(VALIDATION)
X_train_MR, y_train_MR = data['X_train'], data['y_train']
X_val_MR, y_val_MR = data['X_val'], data['y_val']
X_test_MR, y_test_MR = data['X_test'], data['y_test']
n_class_MR = len(np.unique(y_test_MR))

print("Number of train samples: ", X_train_MR.shape[0])
print("Number of val samples: ", X_val_MR.shape[0])
print("Number of test samples: ", X_test_MR.shape[0])

Number of train samples:  4874
Number of val samples:  1625
Number of test samples:  1625


In [7]:
y_train_MR = y_train_MR.reshape(y_train_MR.shape[0], 1)
y_test_MR = y_test_MR.reshape(y_test_MR.shape[0], 1)
y_val_MR = y_val_MR.reshape(y_val_MR.shape[0], 1)

### Get Accuracy

This function computes how well your model performs using accuracy as a metric.

In [8]:
def get_acc(pred, y_test):
  print("test",y_test,"pred",pred)
  return np.mean(y_test==pred)*100

In [ ]:
X_train_CIFAR.shape

(40000, 3072)

# Support Vector Machines (with SGD)

First, you will implement a "soft margin" SVM. In this formulation you will maximize the margin between positive and negative training examples and penalize margin violations using a hinge loss.

We will optimize the SVM loss using SGD. This means you must compute the loss function with respect to model weights. You will use this gradient to update the model weights.

SVM optimized with SGD has 3 hyperparameters that you can experiment with :
- **Learning rate** - similar to as defined above in Perceptron, this parameter scales by how much the weights are changed according to the calculated gradient update. 
- **Epochs** - similar to as defined above in Perceptron.
- **Regularization constant** - Hyperparameter to determine the strength of regularization. In this case it is a coefficient on the term which maximizes the margin. You could try different values. The default value is set to 0.05.

*You* will implement the SVM using SGD in the **models/SVM.py**

The following code: 
- Creates an instance of the SVM classifier class 
- The train function of the SVM class is trained on the training data
- We use the predict function to find the training accuracy as well as the testing accuracy

## Train SVM on CIFAR

In [ ]:
print(n_class_CIFAR)

10


In [ ]:
lr = 0.01
n_epochs = 100
reg_const = 0.05

svm_CIFAR = SVM(n_class_CIFAR, lr, n_epochs, reg_const)
svm_CIFAR.train(X_train_CIFAR, y_train_CIFAR)

NameError: ignored

In [ ]:
pred_svm = svm_CIFAR.predict(X_train_CIFAR)
print('The training accuracy is given by: %f' % (get_acc(pred_svm, y_train_CIFAR)))

### Validate SVM on CIFAR

In [ ]:
pred_svm = svm_CIFAR.predict(X_val_CIFAR)
print('The validation accuracy is given by: %f' % (get_acc(pred_svm, y_val_CIFAR)))

### Test SVM on CIFAR

In [ ]:
pred_svm = svm_CIFAR.predict(X_test_CIFAR)
print('The testing accuracy is given by: %f' % (get_acc(pred_svm, y_test_CIFAR)))

## Train SVM on Mushroom

In [ ]:
"""Support Vector Machine (SVM) model."""

import numpy as np
from random import random
from sklearn.utils import shuffle


class SVM:
    def __init__(self, n_class: int, lr: float, epochs: int, reg_const: float):
        """Initialize a new classifier.

        Parameters:
            n_class: the number of classes
            lr: the learning rate
            epochs: the number of epochs to train for
            reg_const: the regularization constant
        """
        # Size same as X
        self.w = None  # TODO: change this: OK
        self.alpha = lr
        self.epochs = epochs
        self.reg_const = reg_const
        self.n_class = n_class

    def distances(self, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
        N = X_train.shape[0]
        y_train.reshape((N,1))
        dist = 1 - y_train * (np.dot(X_train, self.w))
        dist[dist < 0] = 0
        return dist

    def cost(self, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
        N = X_train.shape[0]
        dist = self.distances(X_train, y_train)
        hinge_loss = 1/reg_const * np.sum(dist) / N
        cost = 1/2 * np.dot(self.w.T, self.w) + hinge_loss
        return cost

    def calc_gradient(self, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
        """Calculate gradient of the svm hinge loss.

        Inputs have dimension D, there are C classes, and we operate on
        mini-batches of N examples.

        Parameters:
            X_train: a numpy array of shape (N, D) containing a mini-batch
                of data
            y_train: a numpy array of shape (N,) containing training labels;
                y[i] = c means that X[i] has label c, where 0 <= c < C

        Returns:
            the gradient with respect to weights w; an array of the same shape
                as w
        """
        N = X_train.shape[0]
        cost = self.cost(X_train, y_train)

        dw = np.zeros(self.w.shape)
        # print('dw ', dw.shape)
        dist = self.distances(X_train, y_train)
        # print('dist ', dist.shape)

        for i, d in enumerate(dist):
            d = d.item()
            # print('d ', d.shape)
            # print('w ', self.w.shape)
            # print('y ', y_train[i].shape)
            # print('x ', X_train[i].shape)
            x = X_train[i].reshape(X_train.shape[1], 1)
            y = y_train[i].item()
            if max(0, d) == 0:
                di = self.w
            else:
                di = self.w - (self.reg_const * y) * x
            dw += di

        dw = dw / N
        return dw

    def train(self, X_train: np.ndarray, y_train: np.ndarray):
        """Train the classifier.

        Hint: operate on mini-batches of data for SGD.

        Parameters:
            X_train: a numpy array of shape (N, D) containing training data;
                N examples with D dimensions
            y_train: a numpy array of shape (N,) containing training labels
        """
        N = X_train.shape[0]
        x_size = X_train.shape[1]
        self.w = np.array([random()] * x_size).reshape(x_size, 1) # Initialize random weights
        # print('W', self.w.shape)

        # grad = self.calc_gradient(X_train, y_train)
        for epoch in range(1, self.epochs + 1):
            X, Y = shuffle(X_train, y_train)
            Y = Y.reshape((y_train.shape[0], 1))
            grad = self.calc_gradient(X, Y)
            self.w = self.w - (self.alpha * grad)
            cost = self.cost(X_train, y_train)
        print(self.w)
        return

    def predict(self, X_test: np.ndarray) -> np.ndarray:
        """Use the trained weights to predict labels for test data points.

        Parameters:
            X_test: a numpy array of shape (N, D) containing testing data;
                N examples with D dimensions

        Returns:
            predicted labels for the data in X_test; a 1-dimensional array of
                length N, where each element is an integer giving the predicted
                class.
        """
        # print(np.sign(X_test @ self.w).shape)
        y = X_test.dot(self.w)
        y_pred = np.sign(y)
        return y_pred


In [ ]:
lr = 0.01
n_epochs = 500
reg_const = 0.05

svm_MR = SVM(n_class_MR, lr, n_epochs, reg_const)
# print(svm_MR.cost(X_train_MR, y_train_MR))
svm_MR.train(X_train_MR, y_train_MR)

[[ 0.00453611]
 [ 0.01446943]
 [-0.00163722]
 [-0.00570398]
 [-0.00900503]
 [ 0.00615319]
 [ 0.00024687]
 [ 0.01761931]
 [-0.08301618]
 [ 0.00296991]
 [-0.01396339]
 [-0.00459187]
 [-0.0050228 ]
 [-0.0140893 ]
 [-0.01416115]
 [ 0.00654776]
 [ 0.00547461]
 [ 0.00255625]
 [-0.02991872]
 [ 0.02025357]
 [ 0.01998891]
 [ 0.02141483]]


In [ ]:
pred_svm = svm_MR.predict(X_train_MR)
print('The training accuracy is given by: %f' % (get_acc(pred_svm, y_train_MR)))

The training accuracy is given by: 71.932704


### Validate SVM on Mushroom

In [ ]:
pred_svm = svm_MR.predict(X_val_MR)
print('The validation accuracy is given by: %f' % (get_acc(pred_svm, y_val_MR)))

The validation accuracy is given by: 71.200000


## Test SVM on Mushroom

In [ ]:
pred_svm = svm_MR.predict(X_test_MR)
print('The testing accuracy is given by: %f' % (get_acc(pred_svm, y_test_MR)))

The testing accuracy is given by: 72.984615


# Softmax Classifier (with SGD)

Next, you will train a Softmax classifier. This classifier consists of a linear function of the input data followed by a softmax function which outputs a vector of dimension C (number of classes) for each data point. Each entry of the softmax output vector corresponds to a confidence in one of the C classes, and like a probability distribution, the entries of the output vector sum to 1. We use a cross-entropy loss on this sotmax output to train the model. 

Check the following link as an additional resource on softmax classification: http://cs231n.github.io/linear-classify/#softmax

Once again we will train the classifier with SGD. This means you need to compute the gradients of the softmax cross-entropy loss function according to the weights and update the weights using this gradient. Check the following link to help with implementing the gradient updates: https://deepnotes.io/softmax-crossentropy

The softmax classifier has 3 hyperparameters that you can experiment with :
- **Learning rate** - As above, this controls how much the model weights are updated with respect to their gradient.
- **Number of Epochs** - As described for perceptron.
- **Regularization constant** - Hyperparameter to determine the strength of regularization. In this case, we minimize the L2 norm of the model weights as regularization, so the regularization constant is a coefficient on the L2 norm in the combined cross-entropy and regularization objective.

You will implement a softmax classifier using SGD in the **models/Softmax.py**

The following code: 
- Creates an instance of the Softmax classifier class 
- The train function of the Softmax class is trained on the training data
- We use the predict function to find the training accuracy as well as the testing accuracy

## Train Softmax on CIFAR

In [ ]:
"""Softmax model."""

import numpy as np


class Softmax:
    def __init__(self, n_class: int, lr: float, epochs: int, reg_const: float):
        """Initialize a new classifier.

        Parameters:
            n_class: the number of classes
            lr: the learning rate
            epochs: the number of epochs to train for
            reg_const: the regularization constant
        """
        self.lr = lr
        self.epochs = epochs
        self.reg_const = reg_const
        self.n_class = n_class
        self.w = np.random.randn(self.n_class,3072)

    def calc_gradient(self, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
        """Calculate gradient of the softmax loss.

        Inputs have dimension D, there are C classes, and we operate on
        mini-batches of N examples.

        Parameters:
            X_train: a numpy array of shape (N, D) containing a mini-batch
                of data
            y_train: a numpy array of shape (N,) containing training labels;
                y[i] = c means that X[i] has label c, where 0 <= c < C

        Returns:
            gradient with respect to weights w; an array of same shape as w
        """
        #Calculating Cross entropy loss
        print("\nweights: ",self.w)
        x = X_train
        z = np.dot(self.w, x) # 10x3072 - 3072x40000 = 10x40000(z)
        # print("\noriginal z", z)
        z -= np.max(z, axis=0) 
        print("\nchanged z",z[0])
        p_sum = np.sum(np.exp(z), axis=0)
        p = np.exp(z) / p_sum # Softmax function 10x40000(p)
        print("\np = " ,p, p_sum)
        L = -1/len(y_train) * np.sum(np.log(p[y_train, range(len(y_train))])) #Cross entropy loss
        R = 0.5 * np.sum(np.multiply(self.w, self.w))
        loss = L + R * reg_const

        #Calculation of Grad
        p[y_train, range(len(y_train))] -= 1
        dW = (1 / len(y_train)) * p.dot(x.T) + (reg_const * self.w)
        return loss, dW

    def train(self, X_train: np.ndarray, y_train: np.ndarray):
        """Train the classifier.

        Hint: operate on mini-batches of data for SGD.

        Parameters:
            X_train: a numpy array of shape (N, D) containing training data;
                N examples with D dimensions
            y_train: a numpy array of shape (N,) containing training labels
        """
        x = X_train.T
        N = x.shape[1]
        loss_calc = []
        for itr in range(1, self.epochs+1):
          loss, grad = self.calc_gradient(x, y_train)
          loss_calc.append(loss)
          print(f"\nLoss in epoch {itr} is {loss}")
          # print(f"\nGrad in epoch {itr} is {grad}")
          self.w -= self.lr * grad 
        print(self.w)
        return

    def predict(self, X_test: np.ndarray) -> np.ndarray:
        """Use the trained weights to predict labels for test data points.

        Parameters:
            X_test: a numpy array of shape (N, D) containing testing data;
                N examples with D dimensions

        Returns:
            predicted labels for the data in X_test; a 1-dimensional array of
                length N, where each element is an integer giving the predicted
                class.
        """
        # TODO: implement me
        y = self.w.dot(X_test.T)
        y_pred = np.argmax(y, axis=0)
        y_pred = y_pred.reshape((len(y_pred),1))
        return y_pred


In [ ]:
lr = 0.01
n_epochs = 10
reg_const = 0.001

softmax_CIFAR = Softmax(n_class_CIFAR, lr, n_epochs, reg_const)
softmax_CIFAR.train(X_train_CIFAR, y_train_CIFAR)


weights:  [[ 1.77706627  0.33480156 -0.16365109 ...  0.92502039 -1.00383399
  -0.13722045]
 [ 0.56878529  1.72280791  1.81602927 ...  0.90680201 -0.7301351
  -1.95709743]
 [-0.67948992  2.11990772 -0.88324979 ... -1.88190067 -0.38278089
  -1.87318037]
 ...
 [ 0.71251437 -0.43394002 -0.43857448 ... -0.62785216  0.54391818
  -0.94684324]
 [ 1.30934016 -0.08950338  0.63694483 ...  1.03237856 -1.20543429
  -0.71745508]
 [-0.87920542  1.56399134 -0.49234303 ... -1.70154434 -0.31455848
   0.01411296]]

changed z [-4253.16125056 -1363.57118122     0.         ... -6159.47816209
 -8379.93936617 -3137.36541679]

p =  [[0.00000000e+000 0.00000000e+000 1.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [9.62467742e-249 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:47: RuntimeWarning: divide by zero encountered in log



Loss in epoch 1 is inf

weights:  [[-16.0309155   -3.0511426    1.43404678 ...  -8.31861539   9.04008318
    1.23989987]
 [ -5.09548311 -15.48176439 -16.32060523 ...  -8.10067995   6.63246878
   17.67467558]
 [  6.12227749 -19.07216947   7.95649262 ...  16.9225588    3.43079181
   16.84505248]
 ...
 [ -6.39859099   3.91860829   3.95904279 ...   5.65490243  -4.89066551
    8.52716486]
 [-11.74556555   0.84560175  -5.69074125 ...  -9.33555861  10.80616685
    6.41568873]
 [  7.93080333 -14.05840392   4.44877652 ...  15.31194304   2.83035132
   -0.1268253 ]]

changed z [-51633.54562697 -48762.7228001  -68974.51972475 ... -16555.69184412
  -8623.65077133 -44844.49266204]

p =  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [1. 1. 1. ... 1. 1. 1.]

Loss in epoch 2 is inf

weights:  [[ 144.33899768   27.52062605  -12.84521487 ...   74.90497508
   -81.32293551  -11.1204224 ]
 [  45.83

In [ ]:
pred_softmax = softmax_CIFAR.predict(X_train_CIFAR)
print('The training accuracy is given by: %f' % (get_acc(pred_softmax, y_train_CIFAR)))

### Validate Softmax on CIFAR

In [ ]:
pred_softmax = softmax_CIFAR.predict(X_val_CIFAR)
print('The validation accuracy is given by: %f' % (get_acc(pred_softmax, y_val_CIFAR)))

### Testing Softmax on CIFAR

In [ ]:
pred_softmax = softmax_CIFAR.predict(X_test_CIFAR)
print('The testing accuracy is given by: %f' % (get_acc(pred_softmax, y_test_CIFAR)))

## Train Softmax on Mushroom

In [14]:
"""Softmax model."""

import numpy as np


class Softmax:
    def __init__(self, n_class: int, lr: float, epochs: int, reg_const: float):
        """Initialize a new classifier.

        Parameters:
            n_class: the number of classes
            lr: the learning rate
            epochs: the number of epochs to train for
            reg_const: the regularization constant
        """
        self.lr = lr
        self.epochs = epochs
        self.reg_const = reg_const
        self.n_class = n_class
        self.w = np.random.randn(self.n_class,22) * 0.1

    def calc_gradient(self, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
        """Calculate gradient of the softmax loss.

        Inputs have dimension D, there are C classes, and we operate on
        mini-batches of N examples.

        Parameters:
            X_train: a numpy array of shape (N, D) containing a mini-batch
                of data
            y_train: a numpy array of shape (N,) containing training labels;
                y[i] = c means that X[i] has label c, where 0 <= c < C

        Returns:
            gradient with respect to weights w; an array of same shape as w
        """
        #Calculating Cross entropy loss
        # print("\nweights: ",self.w)
        x = X_train
        z = np.dot(self.w, x) # 2x22 - 22x4874 = 2x4874(z)
        # print("\noriginal z", z)
        z -= np.max(z, axis=0) 
        # print("\nchanged z",z)
        p = np.exp(z) / np.sum(np.exp(z), axis=0) # Softmax function 2x4874(p)
        log_likelihood = -np.log10(p[y_train, range(len(y_train))])
        L = np.sum(log_likelihood)/len(y_train) #Cross entropy loss
        R = 0.5 * np.sum(np.multiply(self.w, self.w))
        loss = L + R * reg_const

        #Calculation of Grad
        p[y_train, range(len(y_train))] -= 1
        dW = (1 / len(y_train)) * p.dot(x.T) + (reg_const * self.w)
        return loss, dW

    def train(self, X_train: np.ndarray, y_train: np.ndarray):
        """Train the classifier.

        Hint: operate on mini-batches of data for SGD.

        Parameters:
            X_train: a numpy array of shape (N, D) containing training data;
                N examples with D dimensions
            y_train: a numpy array of shape (N,) containing training labels
        """
        x = X_train.T
        N = x.shape[1]
        loss_calc = []
        for itr in range(1, self.epochs+1):
          loss, grad = self.calc_gradient(x, y_train)
          loss_calc.append(loss)
          print(f"\nLoss in epoch {itr} is {loss}")
          # print(f"\nGrad in epoch {itr} is {grad}")
          self.w -= self.lr * grad 
        print(self.w)
        return

    def predict(self, X_test: np.ndarray) -> np.ndarray:
        """Use the trained weights to predict labels for test data points.

        Parameters:
            X_test: a numpy array of shape (N, D) containing testing data;
                N examples with D dimensions

        Returns:
            predicted labels for the data in X_test; a 1-dimensional array of
                length N, where each element is an integer giving the predicted
                class.
        """
        # TODO: implement me
        y = self.w.dot(X_test.T)
        y_pred = np.argmax(y, axis=0)
        y_pred = y_pred.reshape((len(y_pred),1))
        return y_pred


In [15]:
lr = 0.00001
n_epochs = 500
reg_const = 5000

softmax_MR = Softmax(n_class_MR, lr, n_epochs, reg_const)
softmax_MR.train(X_train_MR, y_train_MR)


Loss in epoch 1 is 3296.543893039342

Loss in epoch 2 is 3127.070816054008

Loss in epoch 3 is 2972.9899792232586

Loss in epoch 4 is 2832.9436582764515

Loss in epoch 5 is 2705.690948979557

Loss in epoch 6 is 2590.0975267568747

Loss in epoch 7 is 2485.126413221451

Loss in epoch 8 is 2389.8296346994607

Loss in epoch 9 is 2303.3406701988733

Loss in epoch 10 is 2224.867597996586

Loss in epoch 11 is 2153.686861002505

Loss in epoch 12 is 2089.137581212795

Loss in epoch 13 is 2030.6163628100696

Loss in epoch 14 is 1977.5725317569959

Loss in epoch 15 is 1929.5037670417264

Loss in epoch 16 is 1885.952085082797

Loss in epoch 17 is 1846.5001442295895

Loss in epoch 18 is 1810.767840868561

Loss in epoch 19 is 1778.4091724494485

Loss in epoch 20 is 1749.1093458724386

Loss in epoch 21 is 1722.5821122260468

Loss in epoch 22 is 1698.5673109304432

Loss in epoch 23 is 1676.8286080129303

Loss in epoch 24 is 1657.1514146011907

Loss in epoch 25 is 1639.3409728354557

Loss in epoch 26 

In [17]:
pred_softmax = softmax_MR.predict(X_train_MR)
print('The training accuracy is given by: %f' % (get_acc(pred_softmax, y_train_MR)))

test [[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [0]] pred [[1]
 [1]
 [1]
 ...
 [1]
 [0]
 [1]]
The training accuracy is given by: 40.541650


### Validate Softmax on Mushroom

In [18]:
pred_softmax = softmax_MR.predict(X_val_MR)
print('The validation accuracy is given by: %f' % (get_acc(pred_softmax, y_val_MR)))

test [[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]] pred [[1]
 [1]
 [1]
 ...
 [0]
 [1]
 [1]]
The validation accuracy is given by: 40.000000


### Testing Softmax on Mushroom

In [ ]:
pred_softmax = softmax_MR.predict(X_test_MR)
print('The testing accuracy is given by: %f' % (get_acc(pred_softmax, y_test_MR)))